[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'python310Packages.pipenv', 'nodejs_18', 'npm-9_x']

[phases.install]
cmds = [
    'npm ci',
    'pipenv install --system --deploy'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'cd src && python -m gunicorn wsgi:application --bind 0.0.0.0:$PORT'