[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'nodejs_18', 'npm-9_x']

[phases.install]
cmds = [
    'npm ci',
    'python -m ensurepip --upgrade',
    'python -m pip install --upgrade pip',
    'python -m pip install -r requirements.txt'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'cd src && python -m gunicorn wsgi:application --bind 0.0.0.0:$PORT'