[phases.setup]
nixPkgs = ['nodejs-16_x', 'python310', 'python310Packages.pip']

[phases.install]
cmds = [
    "npm install",
    "pip install --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd src && gunicorn wsgi:application --bind 0.0.0.0:$PORT"