[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'nodejs_18', 'npm-9_x']

[phases.install]
cmds = [
    'npm ci',
    'npm run build',
    'python3 -m pip install --break-system-packages -r requirements.txt'
]

[start]
cmd = 'cd src && python3 -m gunicorn wsgi:application 