[build]
builder = "nixpacks"
buildCommand = "npm run build && pip install -r requirements.txt"

[deploy]
startCommand = "cd src && gunicorn wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "never"