"""Add linkedin_url and github_url to mentor table

Revision ID: a1b2c3d4e5f6
Revises: 58c95bdf89e5
Create Date: 2025-01-06 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '58c95bdf89e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('mentor', sa.Column('github_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor', 'github_url')
    op.drop_column('mentor', 'linkedin_url')
    # ### end Alembic commands ### 