"""empty message

Revision ID: a7b2c17f8f91
Revises: 
Create Date: 2025-06-28 18:54:23.599716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b2c17f8f91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=True),
    sa.Column('about_me', sa.String(length=2500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_code', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=False)
    op.create_table('mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('nick_name', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('what_state', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('about_me', sa.String(length=2500), nullable=True),
    sa.Column('years_exp', sa.String(length=30), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('days', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_oauth_credentials', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_code', sa.String(length=6), nullable=True),
    sa.Column('stripe_account_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_account_id')
    )
    op.create_index(op.f('ix_mentor_email'), 'mentor', ['email'], unique=True)
    op.create_index(op.f('ix_mentor_phone'), 'mentor', ['phone'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('invitee_name', sa.String(length=255), nullable=True),
    sa.Column('invitee_email', sa.String(length=255), nullable=True),
    sa.Column('invitee_notes', sa.Text(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mentor_payout_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAID', 'CONFIRMED', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_MENTOR', 'COMPLETED', 'REFUNDED', 'REQUIRES_RATING', name='bookingstatus'), nullable=False),
    sa.Column('google_meet_link', sa.String(length=255), nullable=True),
    sa.Column('meeting_id', sa.String(length=100), nullable=True),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('meeting_token', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('customer_rating', sa.Integer(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('mentor_notes', sa.Text(), nullable=True),
    sa.Column('rating_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_table('calendar_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.Column('buffer_time', sa.Integer(), nullable=True),
    sa.Column('advance_booking_days', sa.Integer(), nullable=True),
    sa.Column('minimum_notice_hours', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mentor_id')
    )
    op.create_table('customer_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('mentor_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentor_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('scale', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('mentor_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('mentor_unavailability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_photo')
    op.drop_table('mentor_unavailability')
    op.drop_table('mentor_image')
    op.drop_table('mentor_availability')
    op.drop_table('customer_image')
    op.drop_table('calendar_settings')
    op.drop_table('booking')
    op.drop_index(op.f('ix_mentor_phone'), table_name='mentor')
    op.drop_index(op.f('ix_mentor_email'), table_name='mentor')
    op.drop_table('mentor')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
